### PR TITLE
Adding Xplat code coverage for the tests

### PR DESCRIPTION
**Pull request by ShreyasRmsft**

### CODE REVIEW

**Review by vagisha-nidhi — APPROVED** [review]

**Comment by nigurr** [comment]
I don't see any code coverage information is being published!

**Comment by ShreyasRmsft** [comment]
It was getting published via trx :p

**Comment by ShreyasRmsft** [comment]
Now i added cc task

bogus it is, because of race condition :P

**Review by nigurr — APPROVED** [review]

**Comment by nigurr** [comment]
Add it only for Windows (any one platform). Otherwise CC report ll be screwed.

**Pull request merged**
